### ISSUE TITLE
'REACT_APP_SERVICE_HOST' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by ofnya0** [pmckeetx/projectz#1]
Hi Peter,

Thanks for posting your 2 part series on Docker. In part 1, was trying to follow you up to the step to start the UI in git bash with 
$ npm run start

and get the following error:

> ui@0.1.0 start C:\dockerlab\projectz\ui
> REACT_APP_SERVICE_HOST=http://localhost:8080 react-scripts start

'REACT_APP_SERVICE_HOST' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ui@0.1.0 start: `REACT_APP_SERVICE_HOST=http://localhost:8080 react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ui@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myUserAcc\AppData\Roaming\npm-cache\_logs\2020-05-07T23_35_27_534Z-debug.log 

I have google the error and tried a few tricks like:

1. $ npm install
2. $ npm update
3. $ rm -rf node_modules && npm install

4.  uninstalled my node.js
     then went to "C:\Users\myUser\AppData\Roaming
     then deleted the "npm" and "npm-cache" folder
     and re-installed a new version of node.js.

Thanks in advance

**Comment by pmckeetx** [comment]
@ofnya0 I've added the `cross-env` package and updated the package.json file to use it. This should fix the issue. fetch and merge the master branch and you should be fine.

**Comment by ofnya0** [comment]
@pmckeetx it worked. Thanks heaps. I'll continue with tutorial
